### ISSUE TITLE
A minor issue

### ISSUE THREAD

**Issue by ljb121002** [MadryLab/smoothed-vit#1]
Hi, very solid work. But I think there is a typo in the class "MuskProcessor" of /src/utils/custom_models/preprocess.py. 
"ones_mask = torch.where(ones_mask.view(-1) > 0)[0]" this line choose those patches which intersect with ablation columns or blocks, and they belong to [0, 195]. To keep the class token always, the code just adds a 0 at the beginning of ones_mask in the next line. But I think we should first change the range from [0, 195] to [1, 196], then add the 0 :)

**Comment by scoutsaachi** [comment]
Hi!

The full line [here](https://github.com/MadryLab/smoothed-vit/blob/d9f0715f7cd303c9a84ccf32af17743bfa7d2754/src/utils/custom_models/preprocess.py#L91)  is 
`ones_mask = torch.where(ones_mask.view(-1) > 0)[0] + 1`
which does first change the range to [1,196] and then prepends the 0. The code thus already performs exactly as you described.

**Comment by ljb121002** [comment]
Ohh yeah right, sorry about this!
