### ISSUE TITLE
What's the name of attack did you use? In your paper

### ISSUE THREAD

**Issue by Nonbiuld** [MadryLab/smoothed-vit#2]
What kind of attack did you use? In your paper, I can‘t find the method which you use to attack all networks.

**Comment by Hadisalman** [comment]
@Nonbiuld Apologies for late reply, I missed your post. We do not attack our models to evaluate their robustness in this model. We just calculate their certified robust accuracy. The fact that these models are certifiably robust means that we can evaluate their robustness without needing to attack them. Hope this helps!
